generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Coupe
    theme:                 nathanmode
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          coupe
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        num_facture: { label: "N°Facture" }
        tissu: { label: "Qualité" }
        date_commande: { date_format: dd/MM/yyyy }
        livre_le: { date_format: dd/MM/yyyy, label: "Date livraison" }
        piece_categorie: { label: "PF Type" }
        piece: { label: "Produit Fini" }
        nbrelance: {label: Relances}
      list:
        max_per_page: 50
        batch_actions: {}
        sort: [date_commande, desc]
        actions:
          csv: { label: "CSV" }
          _new: ~
        title: "Liste des coupes"
        display: [date_commande, Saison, Fournisseur, Client, tissu, colori, _quantite_type,_quantite, _prix, _livre_le, _fichier_confirmation, _num_facture, _facture, _situation, _nbrelance]
      filter:
        display: [date_commande, saison_id, fournisseur_id, client_id, tissu, colori, piece_categorie, metrage, prix, livre_le, fichier_confirmation, num_facture, fichier, situation, nb_relance]
      form: ~
      edit:
        title: "Modification de la coupe %%tissu%% %%colori%% %%metrage%%"
      new:
        title: "Nouvelle coupe"
