generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Coupe
    theme:                 nathanmode
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          coupe
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        date_commande: { help: "(jj/mm/aaaa)", date_format: dd/MM/yyyy }
        date_livraison: { help: "(jj/mm/aaaa)", date_format: dd/MM/yyyy }
        retard_livraison: { help: "(jj/mm/aaaa)", date_format: dd/MM/yyyy }
        livre_le: { help: "(jj/mm/aaaa)", date_format: dd/MM/yyyy, label: "Expédié le" }
        piece_categorie: { label: "PF Type" }
        piece: { label: "Produit Fini" }
      list:
        max_per_page: 50
        batch_actions: {}
        sort: [date_commande, desc]
        actions:
          csv: { label: "CSV" }
          _new: ~
        title: "Liste des coupes"
        display: [date_commande, Saison, Fournisseur, Client, tissu, colori, _quantite_type,_quantite, prix, _num_facture, _facture, _livre_le, _situation]
      filter:
        display: [date_commande, saison_id, fournisseur_id, client_id, tissu, colori, piece_categorie, metrage, prix, livre_le, num_facture, fichier, situation]
      form: ~
      edit:
        title: "Modification de la coupe %%tissu%% %%colori%% %%metrage%%"
      new:
        title: "Nouvelle coupe"
