<?php

/**
 * BasePrixSpecialDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $prix_special_id
 * @property integer $devise_id
 * @property double $prix
 * @property double $quantite
 * @property PrixSpecial $PrixSpecial
 * @property Devise $Devise
 * 
 * @method integer           getPrixSpecialId()   Returns the current record's "prix_special_id" value
 * @method integer           getDeviseId()        Returns the current record's "devise_id" value
 * @method double            getPrix()            Returns the current record's "prix" value
 * @method double            getQuantite()        Returns the current record's "quantite" value
 * @method PrixSpecial       getPrixSpecial()     Returns the current record's "PrixSpecial" value
 * @method Devise            getDevise()          Returns the current record's "Devise" value
 * @method PrixSpecialDetail setPrixSpecialId()   Sets the current record's "prix_special_id" value
 * @method PrixSpecialDetail setDeviseId()        Sets the current record's "devise_id" value
 * @method PrixSpecialDetail setPrix()            Sets the current record's "prix" value
 * @method PrixSpecialDetail setQuantite()        Sets the current record's "quantite" value
 * @method PrixSpecialDetail setPrixSpecial()     Sets the current record's "PrixSpecial" value
 * @method PrixSpecialDetail setDevise()          Sets the current record's "Devise" value
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePrixSpecialDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('prix_special_detail');
        $this->hasColumn('prix_special_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('devise_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('prix', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('quantite', 'double', null, array(
             'type' => 'double',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PrixSpecial', array(
             'local' => 'prix_special_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Devise', array(
             'local' => 'devise_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}