<?php

/**
 * BaseBon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $saison_id
 * @property integer $fournisseur_id
 * @property integer $commercial_id
 * @property integer $client_id
 * @property integer $devise_montant_id
 * @property integer $devise_fournisseur_id
 * @property integer $devise_commercial_id
 * @property integer $devise_escompte_id
 * @property double $prix_fournisseur
 * @property double $prix_commercial
 * @property double $total_fournisseur
 * @property double $total_commercial
 * @property string $numero
 * @property date $date
 * @property date $echeance
 * @property double $escompte
 * @property double $montant
 * @property double $montant_total
 * @property string $metrage
 * @property string $piece
 * @property string $qualite
 * @property string $fichier
 * @property string $statut
 * @property boolean $actif
 * @property string $type
 * @property string $relation
 * @property date $date_debit
 * @property Saison $Saison
 * @property Fournisseur $Fournisseur
 * @property Commercial $Commercial
 * @property Client $Client
 * @property Devise $DeviseEscompte
 * @property Devise $DeviseMontant
 * @property Devise $DeviseFournisseur
 * @property Devise $DeviseCommercial
 * 
 * @method integer     getSaisonId()              Returns the current record's "saison_id" value
 * @method integer     getFournisseurId()         Returns the current record's "fournisseur_id" value
 * @method integer     getCommercialId()          Returns the current record's "commercial_id" value
 * @method integer     getClientId()              Returns the current record's "client_id" value
 * @method integer     getDeviseMontantId()       Returns the current record's "devise_montant_id" value
 * @method integer     getDeviseFournisseurId()   Returns the current record's "devise_fournisseur_id" value
 * @method integer     getDeviseCommercialId()    Returns the current record's "devise_commercial_id" value
 * @method integer     getDeviseEscompteId()      Returns the current record's "devise_escompte_id" value
 * @method double      getPrixFournisseur()       Returns the current record's "prix_fournisseur" value
 * @method double      getPrixCommercial()        Returns the current record's "prix_commercial" value
 * @method double      getTotalFournisseur()      Returns the current record's "total_fournisseur" value
 * @method double      getTotalCommercial()       Returns the current record's "total_commercial" value
 * @method string      getNumero()                Returns the current record's "numero" value
 * @method date        getDate()                  Returns the current record's "date" value
 * @method date        getEcheance()              Returns the current record's "echeance" value
 * @method double      getEscompte()              Returns the current record's "escompte" value
 * @method double      getMontant()               Returns the current record's "montant" value
 * @method double      getMontantTotal()          Returns the current record's "montant_total" value
 * @method string      getMetrage()               Returns the current record's "metrage" value
 * @method string      getPiece()                 Returns the current record's "piece" value
 * @method string      getQualite()               Returns the current record's "qualite" value
 * @method string      getFichier()               Returns the current record's "fichier" value
 * @method string      getStatut()                Returns the current record's "statut" value
 * @method boolean     getActif()                 Returns the current record's "actif" value
 * @method string      getType()                  Returns the current record's "type" value
 * @method string      getRelation()              Returns the current record's "relation" value
 * @method date        getDateDebit()             Returns the current record's "date_debit" value
 * @method Saison      getSaison()                Returns the current record's "Saison" value
 * @method Fournisseur getFournisseur()           Returns the current record's "Fournisseur" value
 * @method Commercial  getCommercial()            Returns the current record's "Commercial" value
 * @method Client      getClient()                Returns the current record's "Client" value
 * @method Devise      getDeviseEscompte()        Returns the current record's "DeviseEscompte" value
 * @method Devise      getDeviseMontant()         Returns the current record's "DeviseMontant" value
 * @method Devise      getDeviseFournisseur()     Returns the current record's "DeviseFournisseur" value
 * @method Devise      getDeviseCommercial()      Returns the current record's "DeviseCommercial" value
 * @method Bon         setSaisonId()              Sets the current record's "saison_id" value
 * @method Bon         setFournisseurId()         Sets the current record's "fournisseur_id" value
 * @method Bon         setCommercialId()          Sets the current record's "commercial_id" value
 * @method Bon         setClientId()              Sets the current record's "client_id" value
 * @method Bon         setDeviseMontantId()       Sets the current record's "devise_montant_id" value
 * @method Bon         setDeviseFournisseurId()   Sets the current record's "devise_fournisseur_id" value
 * @method Bon         setDeviseCommercialId()    Sets the current record's "devise_commercial_id" value
 * @method Bon         setDeviseEscompteId()      Sets the current record's "devise_escompte_id" value
 * @method Bon         setPrixFournisseur()       Sets the current record's "prix_fournisseur" value
 * @method Bon         setPrixCommercial()        Sets the current record's "prix_commercial" value
 * @method Bon         setTotalFournisseur()      Sets the current record's "total_fournisseur" value
 * @method Bon         setTotalCommercial()       Sets the current record's "total_commercial" value
 * @method Bon         setNumero()                Sets the current record's "numero" value
 * @method Bon         setDate()                  Sets the current record's "date" value
 * @method Bon         setEcheance()              Sets the current record's "echeance" value
 * @method Bon         setEscompte()              Sets the current record's "escompte" value
 * @method Bon         setMontant()               Sets the current record's "montant" value
 * @method Bon         setMontantTotal()          Sets the current record's "montant_total" value
 * @method Bon         setMetrage()               Sets the current record's "metrage" value
 * @method Bon         setPiece()                 Sets the current record's "piece" value
 * @method Bon         setQualite()               Sets the current record's "qualite" value
 * @method Bon         setFichier()               Sets the current record's "fichier" value
 * @method Bon         setStatut()                Sets the current record's "statut" value
 * @method Bon         setActif()                 Sets the current record's "actif" value
 * @method Bon         setType()                  Sets the current record's "type" value
 * @method Bon         setRelation()              Sets the current record's "relation" value
 * @method Bon         setDateDebit()             Sets the current record's "date_debit" value
 * @method Bon         setSaison()                Sets the current record's "Saison" value
 * @method Bon         setFournisseur()           Sets the current record's "Fournisseur" value
 * @method Bon         setCommercial()            Sets the current record's "Commercial" value
 * @method Bon         setClient()                Sets the current record's "Client" value
 * @method Bon         setDeviseEscompte()        Sets the current record's "DeviseEscompte" value
 * @method Bon         setDeviseMontant()         Sets the current record's "DeviseMontant" value
 * @method Bon         setDeviseFournisseur()     Sets the current record's "DeviseFournisseur" value
 * @method Bon         setDeviseCommercial()      Sets the current record's "DeviseCommercial" value
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bon');
        $this->hasColumn('saison_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fournisseur_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('commercial_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('devise_montant_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('devise_fournisseur_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('devise_commercial_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('devise_escompte_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('prix_fournisseur', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('prix_commercial', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('total_fournisseur', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('total_commercial', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('numero', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('echeance', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('escompte', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('montant', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('montant_total', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('metrage', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('piece', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('qualite', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('fichier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('statut', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('actif', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('relation', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('date_debit', 'date', null, array(
             'type' => 'date',
             ));

        $this->setSubClasses(array(
             'Facture' => 
             array(
              'type' => 'Facture',
             ),
             'Credit' => 
             array(
              'type' => 'Credit',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Saison', array(
             'local' => 'saison_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Fournisseur', array(
             'local' => 'fournisseur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Commercial', array(
             'local' => 'commercial_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Devise as DeviseEscompte', array(
             'local' => 'devise_escompte_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Devise as DeviseMontant', array(
             'local' => 'devise_montant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Devise as DeviseFournisseur', array(
             'local' => 'devise_fournisseur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Devise as DeviseCommercial', array(
             'local' => 'devise_commercial_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}