<?php

/**
 * BaseCollectionRetard
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $collection_id
 * @property date $date
 * @property text $observation
 * @property Collection $Collection
 * 
 * @method integer          getCollectionId()  Returns the current record's "collection_id" value
 * @method date             getDate()          Returns the current record's "date" value
 * @method text             getObservation()   Returns the current record's "observation" value
 * @method Collection       getCollection()    Returns the current record's "Collection" value
 * @method CollectionRetard setCollectionId()  Sets the current record's "collection_id" value
 * @method CollectionRetard setDate()          Sets the current record's "date" value
 * @method CollectionRetard setObservation()   Sets the current record's "observation" value
 * @method CollectionRetard setCollection()    Sets the current record's "Collection" value
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCollectionRetard extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('collection_retard');
        $this->hasColumn('collection_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('observation', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('qualite', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('colori', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('piece_categorie', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Collection', array(
             'local' => 'collection_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}