<?php

/**
 * BaseCollection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $saison_id
 * @property integer $fournisseur_id
 * @property integer $commercial_id
 * @property integer $client_id
 * @property integer $devise_fournisseur_id
 * @property integer $devise_commercial_id
 * @property string $paiement
 * @property string $num_commande
 * @property date $date_commande
 * @property string $fichier
 * @property string $situation
 * @property double $prix_fournisseur
 * @property double $prix_commercial
 * @property string $qualite
 * @property string $ecru
 * @property text $observation_general
 * @property text $observation_tirelle
 * @property string $fiche_client
 * @property string $fiche_technique
 * @property text $observation_client
 * @property string $fichier_confirmation
 * @property date $date_livraison
 * @property string $adresse_livraison
 * @property string $reste_a_livrer
 * @property text $observation_livraison
 * @property boolean $commande_soldee
 * @property date $tm_date_expedition
 * @property string $tm_refus_test
 * @property string $tm_validation
 * @property date $tm_date_expedition_coteco
 * @property string $tm_metrage_coteco
 * @property string $tm_validation_coteco
 * @property text $tm_observation
 * @property boolean $production
 * @property date $date_retard
 * @property Saison $Saison
 * @property Fournisseur $Fournisseur
 * @property Commercial $Commercial
 * @property Client $Client
 * @property Devise $DeviseFournisseur
 * @property Devise $DeviseCommercial
 * @property Doctrine_Collection $CollectionDetails
 * @property Doctrine_Collection $CollectionTirelles
 * @property Doctrine_Collection $CollectionRetards
 * @property Doctrine_Collection $CollectionLivraisons
 * 
 * @method integer             getSaisonId()                  Returns the current record's "saison_id" value
 * @method integer             getFournisseurId()             Returns the current record's "fournisseur_id" value
 * @method integer             getCommercialId()              Returns the current record's "commercial_id" value
 * @method integer             getClientId()                  Returns the current record's "client_id" value
 * @method integer             getDeviseFournisseurId()       Returns the current record's "devise_fournisseur_id" value
 * @method integer             getDeviseCommercialId()        Returns the current record's "devise_commercial_id" value
 * @method string              getPaiement()                  Returns the current record's "paiement" value
 * @method string              getNumCommande()               Returns the current record's "num_commande" value
 * @method date                getDateCommande()              Returns the current record's "date_commande" value
 * @method string              getFichier()                   Returns the current record's "fichier" value
 * @method string              getSituation()                 Returns the current record's "situation" value
 * @method double              getPrixFournisseur()           Returns the current record's "prix_fournisseur" value
 * @method double              getPrixCommercial()            Returns the current record's "prix_commercial" value
 * @method string              getQualite()                   Returns the current record's "qualite" value
 * @method string              getEcru()                      Returns the current record's "ecru" value
 * @method text                getObservationGeneral()        Returns the current record's "observation_general" value
 * @method text                getObservationTirelle()        Returns the current record's "observation_tirelle" value
 * @method string              getFicheClient()               Returns the current record's "fiche_client" value
 * @method string              getFicheTechnique()            Returns the current record's "fiche_technique" value
 * @method text                getObservationClient()         Returns the current record's "observation_client" value
 * @method string              getFichierConfirmation()       Returns the current record's "fichier_confirmation" value
 * @method date                getDateLivraison()             Returns the current record's "date_livraison" value
 * @method string              getAdresseLivraison()          Returns the current record's "adresse_livraison" value
 * @method string              getResteALivrer()              Returns the current record's "reste_a_livrer" value
 * @method text                getObservationLivraison()      Returns the current record's "observation_livraison" value
 * @method boolean             getCommandeSoldee()            Returns the current record's "commande_soldee" value
 * @method date                getTmDateExpedition()          Returns the current record's "tm_date_expedition" value
 * @method string              getTmRefusTest()               Returns the current record's "tm_refus_test" value
 * @method string              getTmValidation()              Returns the current record's "tm_validation" value
 * @method date                getTmDateExpeditionCoteco()    Returns the current record's "tm_date_expedition_coteco" value
 * @method string              getTmMetrageCoteco()           Returns the current record's "tm_metrage_coteco" value
 * @method string              getTmValidationCoteco()        Returns the current record's "tm_validation_coteco" value
 * @method text                getTmObservation()             Returns the current record's "tm_observation" value
 * @method boolean             getProduction()                Returns the current record's "production" value
 * @method date                getDateRetard()                Returns the current record's "date_retard" value
 * @method Saison              getSaison()                    Returns the current record's "Saison" value
 * @method Fournisseur         getFournisseur()               Returns the current record's "Fournisseur" value
 * @method Commercial          getCommercial()                Returns the current record's "Commercial" value
 * @method Client              getClient()                    Returns the current record's "Client" value
 * @method Devise              getDeviseFournisseur()         Returns the current record's "DeviseFournisseur" value
 * @method Devise              getDeviseCommercial()          Returns the current record's "DeviseCommercial" value
 * @method Doctrine_Collection getCollectionDetails()         Returns the current record's "CollectionDetails" collection
 * @method Doctrine_Collection getCollectionTirelles()        Returns the current record's "CollectionTirelles" collection
 * @method Doctrine_Collection getCollectionRetards()         Returns the current record's "CollectionRetards" collection
 * @method Doctrine_Collection getCollectionLivraisons()      Returns the current record's "CollectionLivraisons" collection
 * @method Collection          setSaisonId()                  Sets the current record's "saison_id" value
 * @method Collection          setFournisseurId()             Sets the current record's "fournisseur_id" value
 * @method Collection          setCommercialId()              Sets the current record's "commercial_id" value
 * @method Collection          setClientId()                  Sets the current record's "client_id" value
 * @method Collection          setDeviseFournisseurId()       Sets the current record's "devise_fournisseur_id" value
 * @method Collection          setDeviseCommercialId()        Sets the current record's "devise_commercial_id" value
 * @method Collection          setPaiement()                  Sets the current record's "paiement" value
 * @method Collection          setNumCommande()               Sets the current record's "num_commande" value
 * @method Collection          setDateCommande()              Sets the current record's "date_commande" value
 * @method Collection          setFichier()                   Sets the current record's "fichier" value
 * @method Collection          setSituation()                 Sets the current record's "situation" value
 * @method Collection          setPrixFournisseur()           Sets the current record's "prix_fournisseur" value
 * @method Collection          setPrixCommercial()            Sets the current record's "prix_commercial" value
 * @method Collection          setQualite()                   Sets the current record's "qualite" value
 * @method Collection          setEcru()                      Sets the current record's "ecru" value
 * @method Collection          setObservationGeneral()        Sets the current record's "observation_general" value
 * @method Collection          setObservationTirelle()        Sets the current record's "observation_tirelle" value
 * @method Collection          setFicheClient()               Sets the current record's "fiche_client" value
 * @method Collection          setFicheTechnique()            Sets the current record's "fiche_technique" value
 * @method Collection          setObservationClient()         Sets the current record's "observation_client" value
 * @method Collection          setFichierConfirmation()       Sets the current record's "fichier_confirmation" value
 * @method Collection          setDateLivraison()             Sets the current record's "date_livraison" value
 * @method Collection          setAdresseLivraison()          Sets the current record's "adresse_livraison" value
 * @method Collection          setResteALivrer()              Sets the current record's "reste_a_livrer" value
 * @method Collection          setObservationLivraison()      Sets the current record's "observation_livraison" value
 * @method Collection          setCommandeSoldee()            Sets the current record's "commande_soldee" value
 * @method Collection          setTmDateExpedition()          Sets the current record's "tm_date_expedition" value
 * @method Collection          setTmRefusTest()               Sets the current record's "tm_refus_test" value
 * @method Collection          setTmValidation()              Sets the current record's "tm_validation" value
 * @method Collection          setTmDateExpeditionCoteco()    Sets the current record's "tm_date_expedition_coteco" value
 * @method Collection          setTmMetrageCoteco()           Sets the current record's "tm_metrage_coteco" value
 * @method Collection          setTmValidationCoteco()        Sets the current record's "tm_validation_coteco" value
 * @method Collection          setTmObservation()             Sets the current record's "tm_observation" value
 * @method Collection          setProduction()                Sets the current record's "production" value
 * @method Collection          setDateRetard()                Sets the current record's "date_retard" value
 * @method Collection          setSaison()                    Sets the current record's "Saison" value
 * @method Collection          setFournisseur()               Sets the current record's "Fournisseur" value
 * @method Collection          setCommercial()                Sets the current record's "Commercial" value
 * @method Collection          setClient()                    Sets the current record's "Client" value
 * @method Collection          setDeviseFournisseur()         Sets the current record's "DeviseFournisseur" value
 * @method Collection          setDeviseCommercial()          Sets the current record's "DeviseCommercial" value
 * @method Collection          setCollectionDetails()         Sets the current record's "CollectionDetails" collection
 * @method Collection          setCollectionTirelles()        Sets the current record's "CollectionTirelles" collection
 * @method Collection          setCollectionRetards()         Sets the current record's "CollectionRetards" collection
 * @method Collection          setCollectionLivraisons()      Sets the current record's "CollectionLivraisons" collection
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCollection extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('collection');
        $this->hasColumn('saison_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fournisseur_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('commercial_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('devise_fournisseur_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('devise_commercial_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('paiement', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('num_commande', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('date_commande', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('fichier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('situation', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('prix_fournisseur', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('prix_commercial', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('qualite', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('ecru', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('observation_general', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('observation_tirelle', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('fiche_client', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fiche_technique', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('observation_client', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('fichier_confirmation', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('date_livraison', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('adresse_livraison', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('reste_a_livrer', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('observation_livraison', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('commande_soldee', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('tm_date_expedition', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('tm_refus_test', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('tm_validation', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('tm_date_expedition_coteco', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('tm_metrage_coteco', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('tm_validation_coteco', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('tm_observation', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('production', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             ));
        $this->hasColumn('date_retard', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('nb_relance', 'integer', null, array(
             'type' => 'integer'
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Saison', array(
             'local' => 'saison_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Fournisseur', array(
             'local' => 'fournisseur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Commercial', array(
             'local' => 'commercial_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Devise as DeviseFournisseur', array(
             'local' => 'devise_fournisseur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Devise as DeviseCommercial', array(
             'local' => 'devise_commercial_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('CollectionDetail as CollectionDetails', array(
             'local' => 'id',
             'foreign' => 'collection_id'));

        $this->hasMany('CollectionTirelle as CollectionTirelles', array(
             'local' => 'id',
             'foreign' => 'collection_id'));

        $this->hasMany('CollectionRetard as CollectionRetards', array(
             'local' => 'id',
             'foreign' => 'collection_id'));

        $this->hasMany('CollectionLivraison as CollectionLivraisons', array(
             'local' => 'id',
             'foreign' => 'collection_id'));

        $this->hasMany('CreditCommande as CreditCommandes', array(
             'local' => 'id',
             'foreign' => 'collection_id'));
    }
}
