<?php

/**
 * BaseCoupe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $saison_id
 * @property integer $fournisseur_id
 * @property integer $commercial_id
 * @property integer $client_id
 * @property integer $devise_id
 * @property integer $fournisseur_devise_id
 * @property integer $commercial_devise_id
 * @property double $commission_fournisseur
 * @property double $commission_commercial
 * @property integer $facture_id
 * @property integer $commande_id
 * @property string $paiement
 * @property double $prix
 * @property double $montant_facture
 * @property string $num_facture
 * @property string $num_commande
 * @property date $date_commande
 * @property string $tissu
 * @property string $colori
 * @property string $metrage
 * @property string $piece_categorie
 * @property string $piece
 * @property date $date_livraison
 * @property string $retard_livraison
 * @property date $livre_le
 * @property string $fichier
 * @property string $situation
 * @property Saison $Saison
 * @property Fournisseur $Fournisseur
 * @property Commercial $Commercial
 * @property Client $Client
 * @property Devise $Devise
 * @property Devise $DeviseFournisseur
 * @property Devise $DeviseCommercial
 * @property Facture $Facture
 * @property Commande $Commande
 * 
 * @method integer     getSaisonId()               Returns the current record's "saison_id" value
 * @method integer     getFournisseurId()          Returns the current record's "fournisseur_id" value
 * @method integer     getCommercialId()           Returns the current record's "commercial_id" value
 * @method integer     getClientId()               Returns the current record's "client_id" value
 * @method integer     getDeviseId()               Returns the current record's "devise_id" value
 * @method integer     getFournisseurDeviseId()    Returns the current record's "fournisseur_devise_id" value
 * @method integer     getCommercialDeviseId()     Returns the current record's "commercial_devise_id" value
 * @method double      getCommissionFournisseur()  Returns the current record's "commission_fournisseur" value
 * @method double      getCommissionCommercial()   Returns the current record's "commission_commercial" value
 * @method integer     getFactureId()              Returns the current record's "facture_id" value
 * @method integer     getCommandeId()             Returns the current record's "commande_id" value
 * @method string      getPaiement()               Returns the current record's "paiement" value
 * @method double      getPrix()                   Returns the current record's "prix" value
 * @method double      getMontantFacture()         Returns the current record's "montant_facture" value
 * @method string      getNumFacture()             Returns the current record's "num_facture" value
 * @method string      getNumCommande()            Returns the current record's "num_commande" value
 * @method date        getDateCommande()           Returns the current record's "date_commande" value
 * @method string      getTissu()                  Returns the current record's "tissu" value
 * @method string      getColori()                 Returns the current record's "colori" value
 * @method string      getMetrage()                Returns the current record's "metrage" value
 * @method string      getPieceCategorie()         Returns the current record's "piece_categorie" value
 * @method string      getPiece()                  Returns the current record's "piece" value
 * @method date        getDateLivraison()          Returns the current record's "date_livraison" value
 * @method string      getRetardLivraison()        Returns the current record's "retard_livraison" value
 * @method date        getLivreLe()                Returns the current record's "livre_le" value
 * @method string      getFichier()                Returns the current record's "fichier" value
 * @method string      getSituation()              Returns the current record's "situation" value
 * @method Saison      getSaison()                 Returns the current record's "Saison" value
 * @method Fournisseur getFournisseur()            Returns the current record's "Fournisseur" value
 * @method Commercial  getCommercial()             Returns the current record's "Commercial" value
 * @method Client      getClient()                 Returns the current record's "Client" value
 * @method Devise      getDevise()                 Returns the current record's "Devise" value
 * @method Devise      getDeviseFournisseur()      Returns the current record's "DeviseFournisseur" value
 * @method Devise      getDeviseCommercial()       Returns the current record's "DeviseCommercial" value
 * @method Facture     getFacture()                Returns the current record's "Facture" value
 * @method Commande    getCommande()               Returns the current record's "Commande" value
 * @method Coupe       setSaisonId()               Sets the current record's "saison_id" value
 * @method Coupe       setFournisseurId()          Sets the current record's "fournisseur_id" value
 * @method Coupe       setCommercialId()           Sets the current record's "commercial_id" value
 * @method Coupe       setClientId()               Sets the current record's "client_id" value
 * @method Coupe       setDeviseId()               Sets the current record's "devise_id" value
 * @method Coupe       setFournisseurDeviseId()    Sets the current record's "fournisseur_devise_id" value
 * @method Coupe       setCommercialDeviseId()     Sets the current record's "commercial_devise_id" value
 * @method Coupe       setCommissionFournisseur()  Sets the current record's "commission_fournisseur" value
 * @method Coupe       setCommissionCommercial()   Sets the current record's "commission_commercial" value
 * @method Coupe       setFactureId()              Sets the current record's "facture_id" value
 * @method Coupe       setCommandeId()             Sets the current record's "commande_id" value
 * @method Coupe       setPaiement()               Sets the current record's "paiement" value
 * @method Coupe       setPrix()                   Sets the current record's "prix" value
 * @method Coupe       setMontantFacture()         Sets the current record's "montant_facture" value
 * @method Coupe       setNumFacture()             Sets the current record's "num_facture" value
 * @method Coupe       setNumCommande()            Sets the current record's "num_commande" value
 * @method Coupe       setDateCommande()           Sets the current record's "date_commande" value
 * @method Coupe       setTissu()                  Sets the current record's "tissu" value
 * @method Coupe       setColori()                 Sets the current record's "colori" value
 * @method Coupe       setMetrage()                Sets the current record's "metrage" value
 * @method Coupe       setPieceCategorie()         Sets the current record's "piece_categorie" value
 * @method Coupe       setPiece()                  Sets the current record's "piece" value
 * @method Coupe       setDateLivraison()          Sets the current record's "date_livraison" value
 * @method Coupe       setRetardLivraison()        Sets the current record's "retard_livraison" value
 * @method Coupe       setLivreLe()                Sets the current record's "livre_le" value
 * @method Coupe       setFichier()                Sets the current record's "fichier" value
 * @method Coupe       setSituation()              Sets the current record's "situation" value
 * @method Coupe       setSaison()                 Sets the current record's "Saison" value
 * @method Coupe       setFournisseur()            Sets the current record's "Fournisseur" value
 * @method Coupe       setCommercial()             Sets the current record's "Commercial" value
 * @method Coupe       setClient()                 Sets the current record's "Client" value
 * @method Coupe       setDevise()                 Sets the current record's "Devise" value
 * @method Coupe       setDeviseFournisseur()      Sets the current record's "DeviseFournisseur" value
 * @method Coupe       setDeviseCommercial()       Sets the current record's "DeviseCommercial" value
 * @method Coupe       setFacture()                Sets the current record's "Facture" value
 * @method Coupe       setCommande()               Sets the current record's "Commande" value
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCoupe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('coupe');
        $this->hasColumn('saison_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fournisseur_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('commercial_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('devise_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fournisseur_devise_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('commercial_devise_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('commission_fournisseur', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('commission_commercial', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('facture_id', 'integer', null, array(
             'type' => 'integer'
             ));
        $this->hasColumn('commande_id', 'integer', null, array(
             'type' => 'integer'
             ));
        $this->hasColumn('paiement', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('prix', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('montant_facture', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('num_facture', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('num_commande', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('date_commande', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('tissu', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('colori', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('metrage', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('piece_categorie', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('piece', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('date_livraison', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('retard_livraison', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('livre_le', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('fichier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('situation', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('nb_relance', 'integer', null, array(
             'type' => 'integer'
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Saison', array(
             'local' => 'saison_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Fournisseur', array(
             'local' => 'fournisseur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Commercial', array(
             'local' => 'commercial_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Devise', array(
             'local' => 'devise_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Devise as DeviseFournisseur', array(
             'local' => 'fournisseur_devise_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Devise as DeviseCommercial', array(
             'local' => 'commercial_devise_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Facture', array(
             'local' => 'facture_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Commande', array(
             'local' => 'commande_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}
