<?php

/**
 * BaseCredit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCredit extends Bon
{
    public function setUp()
    {
        parent::setUp();
        
    }
}