<?php

/**
 * BaseCreditCommande
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 *
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCreditCommande extends Bon
{
	public function setTableDefinition()
	{
		parent::setTableDefinition();
		$this->hasColumn('collection_id', 'integer', null, array(
				 'type' => 'integer'
				 ));
	}
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Collection', array(
             'local' => 'collection_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

    }
}
