generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PrixSpecial
    theme:                 nathanmode
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          prix_special
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        batch_actions: {}
        actions:
          csv: { label: "CSV" }
          _new: ~
        title: "Liste des prix spéciaux"
        display: [Saison, Fournisseur, Client, article, prix_production, date, _details]
      filter:
        display: [saison_id, fournisseur_id, client_id, article, prix_production, date, details]
        class: false
      form:    ~
      edit:
        title: "Modification du prix special %%article%%"
      new:
        title: "Nouveau prix spécial"
