<?php

/**
 * Client
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Client extends BaseClient
{

    public function __toString()
    {
        
        return $this->raison_sociale;
    }
    public function save(Doctrine_Connection $conn = null)
    {
    	$this->raison_sociale = strtoupper($this->raison_sociale);
        parent::save($conn);
    }
}
