<?php

/**
 * CollectionLivraisonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollectionLivraisonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CollectionLivraisonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CollectionLivraison');
    }

    public function getUploadPath($absolute = false) {

        $path = '/uploads/collection_livraison/';

        if ($absolute) {

            return sfConfig::get('sf_web_dir').$path;
        }

        return $path;
    }
    
    public function getAll() {
        return Doctrine_Query::create()
                ->from('CollectionLivraison cl')
                ->leftJoin('cl.Collection c')
                ->leftJoin('cl.Facture f')
                ->execute();
    }
}