<?php

/**
 * CommercialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommercialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommercialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Commercial');
    }

    public function findByParameters($parameters)
    {

        return $this->findAll();
    }

    public function findFavorites($parameters)
    {
        
        return $this->findAll();
    }
}
