<?php

/**
 * CommercialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommercialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommercialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Commercial');
    }
}