<?php

/**
 * CoupeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CoupeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CoupeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Coupe');
    }

    public function getUploadPath($absolute = false) {

        $path = '/uploads/coupe/';

        if ($absolute) {

            return sfConfig::get('sf_web_dir').$path;
        }

        return $path;
    }
}