<?php

/**
 * CoupeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CoupeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CoupeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Coupe');
    }

    public function getUploadPath($absolute = false) {

        $path = '/uploads/coupe/';

        if ($absolute) {

            return sfConfig::get('sf_web_dir').$path;
        }

        return $path;
    }
    
    public function getBySaisonQualiteNotClient($saisonId, $qualite, $clientId) {
      return $this->createQuery('c')
                  ->addWhere('c.saison_id = ?', $saisonId)
                  ->addWhere('c.tissu = ?', $qualite)
                  ->addWhere('c.client_id != ?', $clientId)
                  ->execute();
    }

    public function getNonLivres($nbJour, $nbRelance) {
      return $this->createQuery('c')
                  ->addWhere('(c.situation = \''.Situations::SITUATION_ATT_CONFIRMATION.'\' OR c.situation = \''.Situations::SITUATION_EN_COURS.'\' )')
                  ->addWhere('c.livre_le <= ?', date('Y-m-d', strtotime("+$nbJour day")))
                  ->addWhere('c.nb_relance = ?', $nbRelance)
                  ->execute();
    }
}
