<?php

/**
 * CreditTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CreditCommandeTable extends BonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CreditTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CreditCommande');
    }

    public function getByCollectionId($collectionId) {
          return Doctrine_Query::create()
                  ->from('Bon b')
                  ->where('b.collection_id', $collectionId)
                  ->fetchOne();
    }
}
