<?php

/**
 * Credit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Credit extends BaseCredit
{


  public function save(Doctrine_Connection $conn = null)
  {

    if (!$this->getPrixFournisseur()) {
    	$this->setPrixFournisseur($this->getFournisseur()->getCommission());
    }
    if (!$this->getPrixCommercial()) {
    	$this->setPrixCommercial($this->getCommercial()->getCommission());
    }
    if ($this->getDeviseFournisseur()->isPourcentage()) {
    	try {
    		$this->setTotalFournisseur($this->getMontant() * $this->getPrixFournisseur() / 100);
    	} catch (Exception $e) {
    		$this->setTotalFournisseur(0);
    	}
    } else {
    	$this->setTotalFournisseur($this->getPrixFournisseur());
    }

    if ($this->getDeviseCommercial()->isPourcentage()) {
    	try {
    		$this->setTotalCommercial($this->getMontant() * $this->getPrixCommercial() / 100);
    	} catch (Exception $e) {
    		$this->setTotalCommercial(0);
    	}
    } else {
    	$this->setTotalCommercial($this->getPrixCommercial());
    }
    $this->setMontantTotal($this->getMontant());
    return parent::save($conn);
  }
}
