<?php

/**
 * DeviseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeviseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeviseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Devise');
    }

    public function getOnlyMoneyDevise() {

        return self::createQuery()->addWhere('is_pourcentage = 0');
    }
}
