<?php

/**
 * FactureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FactureTable extends BonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object FactureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Facture');
    }

    public function getUploadPath($absolute = false) {

        $path = '/uploads/factures/';

        if ($absolute) {

            return sfConfig::get('sf_web_dir').$path;
        }

        return $path;
    }
    
    public function findEnAttente() {
        return Doctrine_Query::create()
                ->from('Facture f')
                ->where('f.statut = ?', StatutsBon::STATUT_EN_ATTENTE)
                ->execute();
    }
}