<?php

/**
 * Facture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Facture extends BaseFacture
{
	const TYPE_COUPE = 'Coupe';
	const TYPE_COLLECTION = 'Collection';
	const TYPE_PRODUCTION = 'Production';

	public function isPayee($date) {
		$this->date_debit = $date;
		$this->statut = StatutsFacture::KEY_PAYEE;
	}
}
