<?php

/**
 * FournisseurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FournisseurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FournisseurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Fournisseur');
    }
    
    public function findByParameters($parameters)
    {
    	$client = (isset($parameters['client']) && !empty($parameters['client']))? $parameters['client'] : null;
    	$from = (isset($parameters['from']) && !empty($parameters['from']))? $parameters['from'] : null;
    	$to = (isset($parameters['to']) && !empty($parameters['to']))? $parameters['to'] : null;
    	if ($client) {
    		$ids = $this->getIdsByClient($client, $from, $to);
    		$query = Doctrine_Query::create()->from('Fournisseur f')->whereIn('f.id', ($ids)? $ids : array(0));
        	return $query->execute();
    	} else {
    		return $this->findAll();
    	}
    }
    
    public function findFavorites($parameters)
    {
    	$client = (isset($parameters['client']) && !empty($parameters['client']))? $parameters['client'] : null;
    	$from = (isset($parameters['from']) && !empty($parameters['from']))? $parameters['from'] : null;
    	$to = (isset($parameters['to']) && !empty($parameters['to']))? $parameters['to'] : null;
    	
    	if ($client) {
    		$ids = $this->getIdsByClient($client, $from, $to, 9);
    		$query = Doctrine_Query::create()->from('Fournisseur f')->whereIn('f.id', ($ids)? $ids : array(0));
    	} else {
    		$query = Doctrine_Query::create()->from('Fournisseur f')->whereIn('f.id', array(1,2,9,52,8,23,41,53,44));
    	}
        return $query->execute();
    }
    
    protected function getIdsByClient($client, $from, $to, $limit = null) {
    	$where = '';
    	if ($from && $to) {
    		$where .= " AND b.date <= '".$to."' AND b.date >= '".$from."'";
    	}
    	$req = "SELECT DISTINCT fournisseur_id FROM commande b WHERE b.client_id = ".$client." AND b.montant > 0".$where." ORDER BY b.montant DESC";
    	if ($limit) {
    		$req .= " LIMIT $limit";
    	}
    	$result = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($req);
    	$ids = array();
    	foreach ($result as $item) {
    		$ids[] = $item['fournisseur_id'];
    	}
    	return $ids;
    }
}