<?php

/**
 * PrixSpecialDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrixSpecialDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrixSpecialDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PrixSpecialDetail');
    }
}