<?php

/**
 * QualiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QualiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QualiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Qualite');
    }

    public function isQualiteExiste($qualite) {

        return count($this->findBy('libelle', $qualite)) > 0;
    }

    public function getTabQualites()
    {
    	$result = array();
    	$qualites = $this->findAll();
    	foreach ($qualites as $qualite) {
    		$result[$qualite->libelle] = $qualite->libelle;
    	}
    	return $result;
    }
}