<?php

/**
 * Saison
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Saison extends BaseSaison
{

    public function __toString() {

        return $this->libelle;
    }

    public function getNextSaison() {
      if (preg_match('/([0-9]{4})$/', $this->libelle, $m)) {
      	return SaisonTable::getInstance()->findOneBy('libelle', 'ETE '.($m[1]+1));
      }
      if (preg_match('/([0-9]{2})$/', $this->libelle, $m)) {
        return SaisonTable::getInstance()->findOneBy('libelle', 'HIVERS '.($m[1]).'/'.($m[1]+1));
      }
      return null;
    }

}
