<?php

/**
 * SaisonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SaisonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SaisonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Saison');
    }
}