generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LabDip
    theme:                 nathanmode
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          lab_dip
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        batch_actions: {}
        actions:
          csv: { label: "CSV" }
          _new: ~
        title: "Liste des lab dip"
        display: [Saison, Fournisseur, Client, article, colori, date_envoi, _statut]
      filter:
        display: [saison_id, fournisseur_id, client_id, article, colori, date_envoi, statut]
      edit:
        title: "Modification du lab dip %%article%%"
      new:
        title: "Nouveau lab dip"
