<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
	public function setTableDefinition()
	{
		parent::setTableDefinition();
		$this->hasColumn('commercial_id', 'integer', null, array(
				 'type' => 'integer'
				 ));
	}

	public function setUp()
	{
			parent::setUp();
 			$this->hasOne('Commercial', array(
			'local' => 'commercial_id',
			'foreign' => 'id',
			'onDelete' => 'SET NULL'));
	}
}
