generator:
  class: sfDoctrineGenerator
  param:
    model_class:           collection
    theme:                 nathanmode
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          collection
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        date_commande: { date_format: dd/MM/yyyy }
        date_livraison: { date_format: dd/MM/yyyy }
        ecrus: {label: Coloris}
        date_retard: {label: Retard, date_format: dd/MM/yyyy}
      list:
        max_per_page: 30
        table_method: queryCollections
        table_count_method: queryCollections
        batch_actions: {}
        actions:
          csv: { label: "CSV" }
          _new: ~
        title: "Liste des commandes de collection"
        display: [Saison, Fournisseur, Client, date_commande, num_commande, date_livraison, date_retard, _situation, qualite, _ecrus]
      filter:
        display: [saison_id, fournisseur_id, client_id, date_commande, num_commande, date_livraison, date_retard, situation, qualite, ecrus]
      form:
        class: CollectionCollectionForm
      edit:
        actions:
          _save: { label: "Valider" }
          save_and_production: { label: "Valider et passer en production" }
          _delete: ~
          _list: ~
      new:
        actions:
          _save: { label: "Valider"}
          _list: ~
