generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CollectionDetail
    theme:                 nathanmode
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          collection
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        cd_saison: {label: Saison}
        cd_date_commande: {label: Date commande}
        cd_num_commande: {label: Num commande}
        cd_fournisseur: {label: Fournisseur}
        cd_client: {label: Client}
        cd_piece: {label: Pièce}
        cd_prix: {label: Prix}
        cd_situation: {label: Situation}
      list:
        max_per_page: 30
        table_method: queryProductionExcluded
        table_count_method: queryProductionExcluded
        batch_actions: {}
        actions:
          csv: { label: "CSV" }
          _new: ~
        title: "Liste des coupes"
        display: [_cd_saison, _cd_date_commande,  _cd_num_commande, _cd_fournisseur, _cd_client, colori, _cd_piece, _cd_prix, _cd_situation]
      form:
        class: CollectionCollectionForm
      edit:
        actions:
          _save: { label: "Valider" }
          save_and_production: { label: "Valider et passer en production" }
          _delete: ~
          _list: ~
      new:
        actions:
          _save: { label: "Valider"}
          _list: ~
