<?php

/**
 * BaseQualite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $libelle
 * 
 * @method string  getLibelle() Returns the current record's "libelle" value
 * @method Qualite setLibelle() Sets the current record's "libelle" value
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQualite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('qualite');
        $this->hasColumn('libelle', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}