<?php

/**
 * BaseLabDipDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $lab_dip_id
 * @property date $date
 * @property string $statut
 * @property string $reference
 * @property LabDip $LabDip
 * 
 * @method integer      getLabDipId()   Returns the current record's "lab_dip_id" value
 * @method date         getDate()       Returns the current record's "date" value
 * @method string       getStatut()     Returns the current record's "statut" value
 * @method string       getReference()  Returns the current record's "reference" value
 * @method LabDip       getLabDip()     Returns the current record's "LabDip" value
 * @method LabDipDetail setLabDipId()   Sets the current record's "lab_dip_id" value
 * @method LabDipDetail setDate()       Sets the current record's "date" value
 * @method LabDipDetail setStatut()     Sets the current record's "statut" value
 * @method LabDipDetail setReference()  Sets the current record's "reference" value
 * @method LabDipDetail setLabDip()     Sets the current record's "LabDip" value
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLabDipDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lab_dip_detail');
        $this->hasColumn('lab_dip_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('statut', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('reference', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LabDip', array(
             'local' => 'lab_dip_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}