<?php

/**
 * BaseLabDip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $saison_id
 * @property integer $fournisseur_id
 * @property integer $client_id
 * @property string $article
 * @property string $colori
 * @property date $date_envoi
 * @property string $statut
 * @property Saison $Saison
 * @property Fournisseur $Fournisseur
 * @property Client $Client
 * @property Doctrine_Collection $LabDipDetails
 * 
 * @method integer             getSaisonId()       Returns the current record's "saison_id" value
 * @method integer             getFournisseurId()  Returns the current record's "fournisseur_id" value
 * @method integer             getClientId()       Returns the current record's "client_id" value
 * @method string              getArticle()        Returns the current record's "article" value
 * @method string              getColori()         Returns the current record's "colori" value
 * @method date                getDateEnvoi()      Returns the current record's "date_envoi" value
 * @method string              getStatut()         Returns the current record's "statut" value
 * @method Saison              getSaison()         Returns the current record's "Saison" value
 * @method Fournisseur         getFournisseur()    Returns the current record's "Fournisseur" value
 * @method Client              getClient()         Returns the current record's "Client" value
 * @method Doctrine_Collection getLabDipDetails()  Returns the current record's "LabDipDetails" collection
 * @method LabDip              setSaisonId()       Sets the current record's "saison_id" value
 * @method LabDip              setFournisseurId()  Sets the current record's "fournisseur_id" value
 * @method LabDip              setClientId()       Sets the current record's "client_id" value
 * @method LabDip              setArticle()        Sets the current record's "article" value
 * @method LabDip              setColori()         Sets the current record's "colori" value
 * @method LabDip              setDateEnvoi()      Sets the current record's "date_envoi" value
 * @method LabDip              setStatut()         Sets the current record's "statut" value
 * @method LabDip              setSaison()         Sets the current record's "Saison" value
 * @method LabDip              setFournisseur()    Sets the current record's "Fournisseur" value
 * @method LabDip              setClient()         Sets the current record's "Client" value
 * @method LabDip              setLabDipDetails()  Sets the current record's "LabDipDetails" collection
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLabDip extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lab_dip');
        $this->hasColumn('saison_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fournisseur_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('article', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('colori', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('date_envoi', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('statut', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Saison', array(
             'local' => 'saison_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Fournisseur', array(
             'local' => 'fournisseur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('LabDipDetail as LabDipDetails', array(
             'local' => 'id',
             'foreign' => 'lab_dip_id'));
    }
}