<?php

/**
 * BaseCommande
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $saison_id
 * @property integer $fournisseur_id
 * @property integer $commercial_id
 * @property integer $client_id
 * @property integer $devise_montant_id
 * @property integer $devise_fournisseur_id
 * @property integer $devise_commercial_id
 * @property double $prix_fournisseur
 * @property double $prix_commercial
 * @property double $total_fournisseur
 * @property double $total_commercial
 * @property string $numero
 * @property date $date
 * @property double $montant
 * @property string $colori
 * @property string $metrage
 * @property string $qualite
 * @property string $situation
 * @property string $relation
 * @property Saison $Saison
 * @property Fournisseur $Fournisseur
 * @property Commercial $Commercial
 * @property Client $Client
 * @property Devise $DeviseMontant
 * @property Devise $DeviseFournisseur
 * @property Devise $DeviseCommercial
 * @property Doctrine_Collection $Coupes
 * @property Doctrine_Collection $CollectionDetails
 * 
 * @method integer             getSaisonId()              Returns the current record's "saison_id" value
 * @method integer             getFournisseurId()         Returns the current record's "fournisseur_id" value
 * @method integer             getCommercialId()          Returns the current record's "commercial_id" value
 * @method integer             getClientId()              Returns the current record's "client_id" value
 * @method integer             getDeviseMontantId()       Returns the current record's "devise_montant_id" value
 * @method integer             getDeviseFournisseurId()   Returns the current record's "devise_fournisseur_id" value
 * @method integer             getDeviseCommercialId()    Returns the current record's "devise_commercial_id" value
 * @method double              getPrixFournisseur()       Returns the current record's "prix_fournisseur" value
 * @method double              getPrixCommercial()        Returns the current record's "prix_commercial" value
 * @method double              getTotalFournisseur()      Returns the current record's "total_fournisseur" value
 * @method double              getTotalCommercial()       Returns the current record's "total_commercial" value
 * @method string              getNumero()                Returns the current record's "numero" value
 * @method date                getDate()                  Returns the current record's "date" value
 * @method double              getMontant()               Returns the current record's "montant" value
 * @method string              getColori()                Returns the current record's "colori" value
 * @method string              getMetrage()               Returns the current record's "metrage" value
 * @method string              getQualite()               Returns the current record's "qualite" value
 * @method string              getSituation()             Returns the current record's "situation" value
 * @method string              getRelation()              Returns the current record's "relation" value
 * @method Saison              getSaison()                Returns the current record's "Saison" value
 * @method Fournisseur         getFournisseur()           Returns the current record's "Fournisseur" value
 * @method Commercial          getCommercial()            Returns the current record's "Commercial" value
 * @method Client              getClient()                Returns the current record's "Client" value
 * @method Devise              getDeviseMontant()         Returns the current record's "DeviseMontant" value
 * @method Devise              getDeviseFournisseur()     Returns the current record's "DeviseFournisseur" value
 * @method Devise              getDeviseCommercial()      Returns the current record's "DeviseCommercial" value
 * @method Doctrine_Collection getCoupes()                Returns the current record's "Coupes" collection
 * @method Doctrine_Collection getCollectionDetails()     Returns the current record's "CollectionDetails" collection
 * @method Commande            setSaisonId()              Sets the current record's "saison_id" value
 * @method Commande            setFournisseurId()         Sets the current record's "fournisseur_id" value
 * @method Commande            setCommercialId()          Sets the current record's "commercial_id" value
 * @method Commande            setClientId()              Sets the current record's "client_id" value
 * @method Commande            setDeviseMontantId()       Sets the current record's "devise_montant_id" value
 * @method Commande            setDeviseFournisseurId()   Sets the current record's "devise_fournisseur_id" value
 * @method Commande            setDeviseCommercialId()    Sets the current record's "devise_commercial_id" value
 * @method Commande            setPrixFournisseur()       Sets the current record's "prix_fournisseur" value
 * @method Commande            setPrixCommercial()        Sets the current record's "prix_commercial" value
 * @method Commande            setTotalFournisseur()      Sets the current record's "total_fournisseur" value
 * @method Commande            setTotalCommercial()       Sets the current record's "total_commercial" value
 * @method Commande            setNumero()                Sets the current record's "numero" value
 * @method Commande            setDate()                  Sets the current record's "date" value
 * @method Commande            setMontant()               Sets the current record's "montant" value
 * @method Commande            setColori()                Sets the current record's "colori" value
 * @method Commande            setMetrage()               Sets the current record's "metrage" value
 * @method Commande            setQualite()               Sets the current record's "qualite" value
 * @method Commande            setSituation()             Sets the current record's "situation" value
 * @method Commande            setRelation()              Sets the current record's "relation" value
 * @method Commande            setSaison()                Sets the current record's "Saison" value
 * @method Commande            setFournisseur()           Sets the current record's "Fournisseur" value
 * @method Commande            setCommercial()            Sets the current record's "Commercial" value
 * @method Commande            setClient()                Sets the current record's "Client" value
 * @method Commande            setDeviseMontant()         Sets the current record's "DeviseMontant" value
 * @method Commande            setDeviseFournisseur()     Sets the current record's "DeviseFournisseur" value
 * @method Commande            setDeviseCommercial()      Sets the current record's "DeviseCommercial" value
 * @method Commande            setCoupes()                Sets the current record's "Coupes" collection
 * @method Commande            setCollectionDetails()     Sets the current record's "CollectionDetails" collection
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommande extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('commande');
        $this->hasColumn('saison_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fournisseur_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('commercial_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('devise_montant_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('devise_fournisseur_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('devise_commercial_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('prix_fournisseur', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('prix_commercial', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('total_fournisseur', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('total_commercial', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('numero', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('montant', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('colori', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('metrage', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('qualite', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('situation', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('relation', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Saison', array(
             'local' => 'saison_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Fournisseur', array(
             'local' => 'fournisseur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Commercial', array(
             'local' => 'commercial_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Devise as DeviseMontant', array(
             'local' => 'devise_montant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Devise as DeviseFournisseur', array(
             'local' => 'devise_fournisseur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Devise as DeviseCommercial', array(
             'local' => 'devise_commercial_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Coupe as Coupes', array(
             'local' => 'id',
             'foreign' => 'commande_id'));

        $this->hasMany('CollectionDetail as CollectionDetails', array(
             'local' => 'id',
             'foreign' => 'commande_id'));
    }
}