generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Commande
    theme:                 nathanmode
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          commande
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        date: { date_format: dd/MM/yyyy }
        total_fournisseur: { label: "Commission société" }
        total_commercial: { label: "Commission commercial" }
      list:
        max_per_page: 50
        sort: [date, desc]
        batch_actions: {}
        actions: {}
        object_actions: { _edit: ~}
        title: "Statistiques commandes"
        display: [Fournisseur, Saison, relation, numero, date, Client, qualite, colori, metrage, montant, total_fournisseur, Commercial, total_commercial]
      filter:
        display: [fournisseur_id, saison_id, relation, numero, date, client_id, qualite, colori, metrage, montant, total_fournisseur, commercial_id, total_commercial]
      form:    ~
      edit:    ~
      new:     ~
