generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Client
    theme:                 nathanmode
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          client
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        telephone: { label: "TVA" }
        code_postal_livraison: { label: "Code postal" }
        ville_livraison: { label: "Ville" }
        code_postal_facturation: { label: "Code postal" }
        ville_facturation: { label: "Ville" }
        emails: { help: "si plusieurs, séparer par des virgules" }
      list:
        batch_actions: {}
        actions:
          csv: { label: "CSV" }
          _new: ~
        title: "Liste des clients"
        display: [raison_sociale, telephone, adresse_livraison, code_postal_livraison, ville_livraison, _condition_paiement, id]
      filter:
        display: [raison_sociale, telephone, adresse_livraison, code_postal_livraison, ville_livraison, condition_paiement, id]
      form:    ~
      edit:
        title: "Modification du client %%raison_sociale%%"
      new:
        title: "Nouveau client"
