<?php

/**
 * BonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bon');
    }
}