<?php

/**
 * CollectionRetardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollectionRetardTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CollectionRetardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CollectionRetard');
    }
}