<?php

/**
 * CollectionTirelleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollectionTirelleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CollectionTirelleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CollectionTirelle');
    }
}