<?php

/**
 * Commande
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    nathanmode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Commande extends BaseCommande
{
	const TYPE_COUPE = 'Coupe';
	const TYPE_COLLECTION = 'Collection';
	const TYPE_PRODUCTION = 'Production';
}
