<?php

/**
 * LabDipDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LabDipDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LabDipDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LabDipDetail');
    }
}