<?php

/**
 * LabDipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LabDipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LabDipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LabDip');
    }
}