<?php

/**
 * PrixSpecialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrixSpecialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrixSpecialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PrixSpecial');
    }
}