# You_can_find_more_information_about_this_file_on_the_symfony_website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default_values
all:
  commerciaux:
    liste:
      Eliott: 10
  situations:
    liste:
      ATT_CONFIRMATION:   "Att confirmation"
      EN_COURS:           "En cours"
      EXPE_TIRELLE:       "Expé tirelle"
      EXPE_TIRELLE_TEST:  "Expé tirelle & att test"
      TIRELLE_VALIDEE:    "Tirelle validée"
      TIRELLE_REFUSEE:    "Tirelle refusée"
      DELAI_RETRAITEMENT: "Délai de retraitement"
      RETARD_LIVRAISON:   "Retard livraison"
      ECRU_A_DESIGNER:    "Ecru a designer"
      ECRU_DESIGNER:      "Ecru soldée"
      RESTE_A_LIVRER:     "Reste à livrer"
      #INSPECTION_COTECO: "Inspection coteco"
      INSPECTION_CCT:     "Inspection CCT"
      #INSPECTION_PROMOTEX: "Inspection promotex"
      #INSPECTION_SGT:     "Inspection SGT"
      INSPECTION_QUALITE: "Inspection qualité"
      INSPECTION_PENDON:  "Inspection pendon"
      ATTENTE_TEST:       "Attente test"
      REFUS_TEST:         "Refus test"
      SOLDEE:             "Soldée"
      ATTENTE_PAIEMENT:   "Attente paiement"
      ATTENTE_LIVRAISON:  "Attente adresse de livraison"
  paiements:
    liste:
      VIREMENT_30_JOURS: "Virement 30 jours"
      VIREMENT_60_JOURS: "Virement 60 jours"
      VIREMENT_90_JOURS: "Virement 90 jours"
  conditions_paiement:
    liste:
      30_JOURS_NET: "30 jours net"
      30_JOURS_FIN_DE_MOIS: "30 jours fin de mois"
      30_JOURS_FIN_DE_MOIS_4_ESCOMPTE: "30 jours fin de mois 4% d'escompte"
      60_JOURS_NET: "60 jours net"
      60_JOURS_FIN_DE_MOIS: "60 jours fin de mois"
      60_JOURS_FIN_DE_MOIS_10: "60 jours fin de mois le 10"
      90_JOURS_NET: "90 jours net"
      90_JOURS_LE_MOIS_10: "90 jours le mois du 10"
      90_JOURS_FIN_DE_MOIS: "90 jours fin de mois"
      90_JOURS_FIN_DE_MOIS_10: "90 jours fin de mois le 10"
      PAIEMENT_AVANCE: "Paiement d'avance"
      PAIEMENT_AVANCE_2_PERCENT_ESCOMPTE: "Paiement d'avance 2% d'escompte"
      PAIEMENT_AVANCE_3_PERCENT_ESCOMPTE: "Paiement d'avance 3% d'escompte"
      PAIEMENT_AVANCE_4_PERCENT_ESCOMPTE: "Paiement d'avance 4% d'escompte"
      PAIEMENT_AVANCE_5_PERCENT_ESCOMPTE: "Paiement d'avance 5% d'escompte"
      LC: "L/C"
      LC_A_60_JOURS: "L/C à 60 jours"
      LC_A_90_JOURS: "L/C à 90 jours"
      CASH_ON_DELIVERY: "Cash on delivery"
      30_POURCENT_70_POURCENT: "30% à 10jrs et 70% à 60jrs"
      50_POURCENT_50_POURCENT: "50% à 10jrs et 50% à 60jrs"
  statuts:
    liste:
      REFUS: "Refus"
      EN_ATTENTE: "En attente"
      VALIDE: "Validé"
  statuts_lab_dip:
    liste:
      EN_COURS: "En cours"
      EXPE_CLIENT: "Expé client"
      REFUSE: "Refusé"
      ANNULE: "Annulé"
      VALIDE: "Validé"
  statuts_facture:
    liste:
      #EN_ATTENTE: "En attente"
      #ECHUE: "Echue"
      PAYEE: "Payée"
      NON_PAYEE: "Non payée"
      #ERREUR: "Erreur"
  statuts_credit:
    liste:
      EN_ATTENTE: "En attente"
      DEDUITE: "Deduite"
  piece_categories:
    liste:
      DOUBLE_FACE: "Double face"
      MAILLE: "Maille"
      DOUDOUNE: "Doudoune"
      PARKAS: "Parkas"
      ROBE: "Robe"
      ACCESSOIRES: "Accessoires"
      AUTRE: "Autre"
