qualite:
  class: sfDoctrineRouteCollection
  options:
    model:                Qualite
    module:               qualite
    prefix_path:          /qualite
    column:               id
    with_wildcard_routes: true

commande:
  class: sfDoctrineRouteCollection
  options:
    model:                Commande
    module:               commande
    prefix_path:          /commande
    column:               id
    with_wildcard_routes: true

collection_collection_stats:
  class: sfDoctrineRouteCollection
  options:
    model:                Collection
    module:               collection_stats
    prefix_path:          /collection_stats
    column:               id
    with_wildcard_routes: true

coupe_coupe_stats:
  class: sfDoctrineRouteCollection
  options:
    model:                Coupe
    module:               coupe_stats
    prefix_path:          /coupe_stats
    column:               id
    with_wildcard_routes: true

bon:
  class: sfDoctrineRouteCollection
  options:
    model:                Bon
    module:               bon
    prefix_path:          /bon
    column:               id
    with_wildcard_routes: true

credit:
  class: sfDoctrineRouteCollection
  options:
    model:                Credit
    module:               credit
    prefix_path:          /credit
    column:               id
    with_wildcard_routes: true

facture_facure_payee:
  class: sfDoctrineRouteCollection
  options:
    model:                Facture
    module:               facure_payee
    prefix_path:          /facture_payee
    column:               id
    with_wildcard_routes: true

facture:
  class: sfDoctrineRouteCollection
  options:
    model:                Facture
    module:               facure
    prefix_path:          /facure
    column:               id
    with_wildcard_routes: true

collection_production:
  class: sfDoctrineRouteCollection
  options:
    model:                Collection
    module:               production
    prefix_path:          /production
    column:               id
    with_wildcard_routes: true

collection:
  class: sfDoctrineRouteCollection
  options:
    model:                collection
    module:               collection
    prefix_path:          /collection
    column:               id
    with_wildcard_routes: true

collectiondetails:
  class: sfDoctrineRouteCollection
  options:
    model:                collectionDetails
    module:               collectiondetails
    prefix_path:          /collectiondetails
    column:               id
    with_wildcard_routes: true

prix_special:
  class: sfDoctrineRouteCollection
  options:
    model:                PrixSpecial
    module:               prix_special
    prefix_path:          /prix_special
    column:               id
    with_wildcard_routes: true

lab_dip:
  class: sfDoctrineRouteCollection
  options:
    model:                LabDip
    module:               lab_dip
    prefix_path:          /lab_dip
    column:               id
    with_wildcard_routes: true

coupe_ligne_update:
  url:   /coupe/ligne-update
  param: { module: coupe, action: ligneupdate }

coupe:
  class: sfDoctrineRouteCollection
  options:
    model:                Coupe
    module:               coupe
    prefix_path:          /coupe
    column:               id
    with_wildcard_routes: true

commercial:
  class: sfDoctrineRouteCollection
  options:
    model:                Commercial
    module:               commercial
    prefix_path:          /commercial
    column:               id
    with_wildcard_routes: true

fournisseur:
  class: sfDoctrineRouteCollection
  options:
    model:                Fournisseur
    module:               fournisseur
    prefix_path:          /fournisseur
    column:               id
    with_wildcard_routes: true

client:
  class: sfDoctrineRouteCollection
  options:
    model:                Client
    module:               client
    prefix_path:          /client
    column:               id
    with_wildcard_routes: true

# Commercial activity
activite:
  url:   /commercial-activity
  param: { module: activite, action: index }
modalClient:
  url:   /commercial-activity/modal-client
  param: { module: activite, action: clientContentModal }
modalFournisseur:
  url:   /commercial-activity/modal-fournisseur
  param: { module: activite, action: fournisseurContentModal }
modalCommercial:
  url:   /commercial-activity/modal-commercial
  param: { module: activite, action: commercialContentModal }
activiteRapport:
  url:   /commercial-activity/rapport
  param: { module: activite, action: rapport }
activiteRapports:
  url:   /commercial-activity/rapports
  param: { module: activite, action: rapports }
activiteclient:
  url:   /commercial-activity/client
  param: { module: activite, action: client }
activiteglobal:
  url:   /commercial-activity/global
  param: { module: activite, action: global }

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: client, action: index }
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*


