generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Collection
    theme:                 nathanmode
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          collection_production
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        ecrus: {label: Coloris}
        date_commande: { date_format: dd/MM/yyyy }
        date_livraison: { date_format: dd/MM/yyyy }
        date_retard: {label: Retard, date_format: dd/MM/yyyy}
        nbrelance: {label: Relances}
      list:
        max_per_page: 30
        table_method: queryProductions
        table_count_method: queryProductions
        batch_actions: {  }
        actions:
          _new: ~
        title: "Liste des commandes de production"
        display: [Saison, Fournisseur, Client, date_commande, num_commande, date_livraison, date_retard, _situation, qualite, _ecrus, _nbrelance]
      filter:
        display: [saison_id, fournisseur_id, client_id, date_commande, num_commande, date_livraison, date_retard, situation, qualite, ecrus, nb_relance]
      form:
        class: ProductionCollectionForm
      edit:
        actions:
          _save: { label: "Valider" }
          _delete: ~
          _list: ~
      new:
        actions:
          _save: { label: "Valider" }
          _list: ~
