generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Commercial
    theme:                 nathanmode
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          commercial
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        batch_actions: {}
        actions:
          csv: { label: "CSV" }
          _new: ~
        title: "Liste des commerciaux"
        display: [nom, prenom, email, telephone, commission, Devise]
      filter:
        display: [nom, prenom, email, telephone, commission, devise_id]
      form:
        display: [nom, prenom, email, telephone, commission, devise_id]
      edit:
        title: "Modification du commercial %%prenom%% %%nom%%"
      new:
        title: "Nouveau commercial"
